### ISSUE TITLE
Crash "Read from location 0000000000000000 caused an access violation"

### ISSUE THREAD

**Issue by Jeceratops** [linuxgurugamer/AutomatedScreenshots#6]
Due to the glitching found in RSS RO, I downloaded this mod to do automatic saves, after some funny crashes, 3 in a row, I sent the error log in the RSS RO that identified this mod as the cupript
[error.log](https://github.com/linuxgurugamer/AutomatedScreenshots/files/5071025/error.log)

**Comment by linuxgurugamer** [comment]
First, you should ALWAYS provide the full Player.log, what you did provide was useless.

I would first suggest installing the ZeroMiniAVC, as the MiniAVC is broken in all current versions of KSP.  It tends to cause the game to crash in similiar ways to this.

If after installing it, you still have problems, then reopen this and upload the full Player.Log.

**Comment by siimav** [comment]
That particular crash log isn't the best example because it also contains KerbalKonstructs in the stacktrace. I've also seen logs for similar crashes where the stacktrace clearly indicates that AutomatedScreenshots is the culprit. 
The reason for those is simple - you just can't call `GamePersistence.SaveGame` from a thread that isn't the main one. The method calls that happen just aren't thread safe and most of the times game will crash on logging calls.

**Comment by 1VELVE1** [comment]
Here are both crash logs where I experienced a similar issue.
[Player & Error_logs.zip](https://github.com/linuxgurugamer/AutomatedScreenshots/files/5764768/Player.Error_logs.zip)
